sudo: required

env:
  - COMPILER=dmd
  - COMPILER=ldc2

services:
  - docker

before_install:
  - docker build -t nexor/dvardumper -f Dockerfile.travisci .
  - docker images

script:
  - docker run -it --rm nexor/dvardumper $COMPILER --version
  - docker run -it --rm nexor/dvardumper dub test --compiler=$COMPILER
  - docker run -it --rm nexor/dvardumper dub build -b release --compiler=$COMPILER

notifications:
  email: false
